var homes = [
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 1,
        "num": "001",
        "title": "Кори Ниязова 1в2/4/6 Спец планировка",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        "type": ["Kvartira"],
        "price": 68000, 
        "rooms": 2,   
        "release_date": 1632827972348, 
        "area": "60 m.kv",
        "overview": "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 2,
        "num": "002",
        "title": "Продажа квартиры в новостройке",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/wyac6ia6z48m3-UZ/image;s=1000x700",
        "type": ["Kvartira", "Yangi uylar"],
        "price": 125000, 
        "rooms": 3,   
        "release_date": 1632827972948,
        "area": "75 m.kv",
        "overview": "Kvartirada bor: Muzlatkich, Televizor, Konditsioner, Kir yuvish mashinasi, Oshxona, Balkon",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 3,
        "num": "003",
        "title": "Продаётся Евро Дом 2сот 5ком",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/cenn8yqp02ss2-UZ/image;s=1000x700",
        "type": ["Yangi uylar", "Hovli"],
        "price": 79999, 
        "rooms": 5,   
        "release_date": 1632825972348,
        "area": "200 m.kv",
        "overview": "Uyda / Uchastkada bor: Ertoʻla, omborcha, Garaj, Maishiy texnika, Kanalizatsiya, Tomorqa",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 4,
        "num": "004",
        "title": "Аренда Abay Korzinga 3 хона оилага берилади",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/fmr29kbpl8jn1-UZ/image;s=1000x700",
        "type": ["Kvartira", "Ijara"],
        "price": 350, 
        "rooms": 3,   
        "release_date": 1652827972348,
        "area": "78 m.kv",
        "overview": "Kvartirada bor: Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Oshxona, Balkon",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 5,
        "num": "005",
        "title": "Oilaga Shinam Xonadon",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/l4i7yeojo7hl1-UZ/image;s=1000x700",
        "type": ["Hovli"],
        "price": 49000, 
        "rooms": 4,   
        "release_date": 1632427972348,
        "area": "200 m.kv",
        "overview": "Kvartirada bor: Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 6,
        "num": "006",
        "title": "Продается земля на Юнусабаде",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/s1e6dsn2chjn2-UZ/image;s=1000x700",
        "type": ["Hovli", "Yer uchastkalar",],
        "price": 14000, 
        "rooms": 0,   
        "release_date": 1632823972348,
        "area": "500 m.kv",
        "overview": "Kommunikatsiyalar: Elektr quvvati, Suv, Gaz, Isitish tizimi, Kanalizatsiya, Internet, Telefon",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 7,
        "num": "007",
        "title": "Аренда Срочно!! ТРЦ Некст 1/2/4",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/xtxdhc46ctf63-UZ/image;s=1000x700",
        "type": ["Kvartira", "Ijara", "Yangi uylar",],
        "price": 500, 
        "rooms": 1,   
        "release_date": 1632227972348,
        "area": "50 m.kv",
        "overview": "Аренда Срочно!! ТРЦ Некст 1/2/4 Новый Евролюкс Full Hi-Tech Аппартамент Цена: 500$",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 8,
        "num": "008",
        "title": "Продается срочно квартира на Nest one",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        "type": ["Kvartira", "Yangi uylar",],
        "price": 97000, 
        "rooms": 2,   
        "release_date": 1632627972348,
        "area": "57 m.kv",
        "overview": "Yaqinida joylashgan: Kasalxona, poliklinika, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar, Park, yashil zona, Koʻngilochar muassasalar, Restoran, kafelar, turargoh, Supermarket, doʻkonlar, Maktab",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 9,
        "num": "009",
        "title": "2х комн. кв. сдается в аренду.",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/ljrtkvtkjfuw2-UZ/image;s=1000x700",
        "type": ["Kvartira", "Ijara",],
        "price": 1500, 
        "rooms": 2,   
        "release_date": 1632827572348,
        "area": "70 m.kv",
        "overview": "Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 10,
        "num": "0010",
        "title": "ВЫГОДНОЕ ПРЕДЛОЖЕНИЕ Продажа Котеджи",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/hqzxn9xn9mxw1-UZ/image;s=1000x700",
        "type": ["Hovli", "Yangi uylar"],
        "price": 140000, 
        "rooms": 3,   
        "release_date": 1632427972348,
        "area": "209 m.kv",
        "overview": "Связь Aloqa uchun +99890 928 09 88 отдела продаж Расположение/Manzil Ташкент, Зангиатинский район, улица Хамжихат  Адрес главного офиса отдела продаж, где вам дадут полную консультацию по всем интересующим вас вопросам: Ташкент, Ц1, улица Махтумкули, 48.",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 11,
        "num": "0011",
        "title": "Большой новый особняк в элитном районе",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/x2nupym3y7en1-UZ/image;s=1000x700",
        "type": ["Hovli",],
        "price": 800000, 
        "rooms": 7,   
        "release_date": 1632827972348,
        "area": "1000 m.kv",
        "overview": "Благоустройство дома: электричество, отопление, газ, водопровод +998908083663",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 12,
        "num": "0012",
        "title": "Срочно Продаю Квартиру На Чиланзаре 20",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/yo5ukolqc5gh3-UZ/image;s=1000x700",
        "type": ["Kvartira"],
        "price": 13300, 
        "rooms": 1,   
        "release_date": 1632127972348,
        "area": "19 m.kv",
        "overview": "#Район - Чиланзар, 20 Возле Мечети Илон Ота Бывшее общежитие 1/3/4 , площадь 19 кв м² Внутри газовая плита Цена 13.000 $",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 13,
        "num": "0013",
        "title": "Продается помещение",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/g9lpcw5h52ni-UZ/image;s=1000x700",
        "type": ["Kvartira"],
        "price": 1000000, 
        "rooms": 1,   
        "release_date": 1632857952348,
        "area": "1000 m.kv",
        "overview": "Koʻchmas mulk turi: Do’konlar/butiklar, Salonlar, Ofislar, Erkin maqsaddagi xona-joylar, Binoning bir qismi, Boshqa",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 14,
        "num": "0014",
        "title": "Аренда Общежитие 1/3/4 Ялангач",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/gi64kyxfvlw32-UZ/image;s=1000x700",
        "type": ["Kvartira", "Ijara",],
        "price": 170, 
        "rooms": 1,   
        "release_date": 1631427972348,
        "area": "30 m.kv",
        "overview": "аренда квартира Район - мирзо Улугбек  Ориентир - Мирзо Улугбекская налоговая, кательная",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 15,
        "num": "0015",
        "title": "Хайтек дача чарваке",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/2ut8td3dqfx4-UZ/image;s=1000x700",
        "type": ["Dacha", "Ijara",],
        "price": 180, 
        "rooms": 5,   
        "release_date": 1632827792348,

        "area": "800 m.kv",
        "overview": "Бассейн зимний с обагревом10х4, сауна финский, 3 спальни, всего 12 койка. Летный басейн 12х6м. Сони плейстешн 4, караоке, настольный теннис, настольный футбол, и другие условии есть.",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 16,
        "num": "0016",
        "title": "Зимняя, Уютная дача на природе.",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/1ck6pwlphss12-UZ/image;s=1000x700",
        "type": ["Dacha", "Ijara"],
        "price": 120, 
        "rooms": 8,   
        "release_date": 1631417972348,
        "area": "1400 m.kv",
        "overview": "Суббота и Воскресенье по 1500,000 Зимняя дача со всеми домашними удобствами только для вас и для вашей семьи.",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 17,
        "num": "0017",
        "title": "Зудлик билан уй сотилади",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/w1pwttpngfyw1-UZ/image;s=1000x700",
        "type": ["Hovli",],
        "price": 70000, 
        "rooms": 6,   
        "release_date": 1632827972348,
        "area": "400 m.kv",
        "overview": "Зудлик билан ЯНГИ куриб битказилган ховли уй сотилади, яшаш учун хамма шароитлари бор 4 соток, 6 хона, ошхона, алохида ванна, хаммом, хожатхона Газ, сув, свет 4 фасл муаммосиз Уй ичлари кишда иссик, ёзда салкин Уй мебель ва жихозлари билан сотилади.",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 18,
        "num": "0018",
        "title": "Кора Ниязова 1в2/4/6 Спец планировка",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/47o50zh9ccdc1-UZ/image;s=1000x700",
        "type": ["Kvartira"],
        "price": 68000, 
        "rooms": 2,   
        "release_date": 1632827972348,
        "area": "60 m.kv",
        "overview": "Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 19,
        "num": "0019",
        "title": "Продается квартира в Сергелях",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/xkgweduc35i23-UZ/image;s=1000x700",
        "type": ["Hovli", "Kvartira", "Yangi uylar"],
        "price": 35000, 
        "rooms": 3,   
        "release_date": 1632827279348,
        "area": "77 m.kv",
        "overview": "Продается квартира в Сергелях на 2ом этаже+мансарда. Квартира двухэтажная. На 1ом этаже есть перегородки(кухня,1комната и ванная),на мансарде перегородок нет. можно сделать общее 3 комнаты,2 ванные. Дом расположен в элитной махалле рядом с Корзинкой,РОВД, Хокимиатом. Рядом в садиком Мерри Поппинс. Вся инфраструктура в шаговой доступности Супер вариант для проживания . Квартира своя. Срочно. Ключи в день оформления.",
        },
    {
        // "Hovli", "Kvartira", "Dacha", "Ijara", "Yer uchastkalar", "Yangi uylar", "Shaxsiy",
    //"Makler"
        "id": 20,
        "num": "0020",
        "title": "Дом уй сотиладиган жойлари",
        "img": "https://apollo-olx.cdnvideo.ru/v1/files/jfhd33wkm4rp-UZ/image;s=1000x700",
        "type": ["Kvartira"],
        "price": 40000, 
        "rooms": 5,   
        "release_date": 1632827972348,
        "area": "200 m.kv",
        "overview": "Янги участка ремонти бн ярим план эски машина бозор ёнида",
        },
    ]